name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.2
  flutter_dotenv: ^5.2.1
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon.png
    - assets/splash.png

# ðŸ”¥ APP ICON SETTINGS
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

# ðŸ”¥ SPLASH SCREEN SETTINGS
flutter_native_splash:
  android: true
  ios: true
  color: "#000000"
  image: assets/splash.png
  android_gravity: center
  ios_content_mode: center
